---
# network
network_ethernet_interfaces:
  - device: eth0
    bootproto: static
    address: "{{ admin_ip }}"
    netmask: 255.255.192.0
    gateway: "{{ admin_ip_gateway }}"
  - device: eth1
    bootproto: static
    address: "{{ sp_ip }}"
  - device: eth2
    bootproto: static
    address: "{{ sc_ip }}"
    
# ceph-common
ceph_repo_enable: True
ceph_repo_baseurl: "http://172.23.11.2/repo/ceph/rpm-firefly/el7/"

ceph_cluster_name: "ceph"
ceph_fsid: "cc546e6b-52ab-456b-8283-adff1cd61bce"
ceph_mon_members: "ceph01, ceph02, ceph03"
cep_mon_host: "10.0.2.31,10.0.2.32,10.0.2.33"
ceph_public_network: "10.0.2.0/24"
ceph_cluster_network: "10.0.3.0/24"

# openstack
openstack_config: True

# Monitor options

monitor_secret: AQAnV5dWAAAAABAA/gEcrn76zFfFBp8NTdxfNQ==

# cephx options
cephx: True


# Devices to be used as OSDs
devices:
  - /dev/vdb

# Use 'None' to undefined the variable.
# Using 'None' will colocate both journal and data on the same disk
# creating a partition at the beginning of the device
#
#journal_device: "/dev/sdb"